name: 🚀 Deploy website on push on Main
on:
 push:
  branches:
   - main
 
jobs:
  web-deploy:
    name: 🎉 Deploy on Main
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        npm install --legacy-peer-deps
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:          
        local-dir: ./build/
        server: ${{ secrets.host_prod }}
        username: ${{ secrets.ftp_user_prod }}
        password: ${{ secrets.ftp_password_prod }}
        
        
